# Generated by Django 3.1.6 on 2021-02-20 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210220_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='expiry',
            field=models.DateField(default=datetime.date(2021, 12, 31)),
        ),
    ]
