# Generated by Django 3.1.6 on 2021-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_addproduct_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='base_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
